### ISSUE TITLE
The saveFile callback does not get called on Cancel in Mac OS X 10.9.2

### ISSUE THREAD

**Issue by sompylasar** [exos/node-webkit-fdialogs#2]
The callback should have been called with an error that no file was selected. Looks like no change event occurs on the input (nothing really changes).

Could you please incorporate this hack: https://github.com/nwjs/nw.js/issues/292#issuecomment-51085378 or tell me where in your code it should likely be inserted (I suspect `_createElement`).

Thanks in advance!

**Comment by exos** [comment]
Thanks for the data, I'm very bussy these days. 

I created a branch for this issue called _features/#2_, the commit is [here](https://github.com/exos/node-webkit-fdialogs/commit/4ba597c44ad4162f8c66a56e4a5d05636d489f0).

I do not have the means to test it right now. If you can test it and share your results, I'd rather thanked. 

I will try to test it during this days.

_Sorry my poor english_

**Comment by sompylasar** [comment]
@exos Thanks a lot! I'll test this in a day or so.

**Comment by exos** [comment]
@sompylasar Do you check it? if works well I merge with master.

**Comment by sompylasar** [comment]
@exos Sorry for the delay, I haven't got to this issue earlier. Thanks for the reminder!
I've just tested the fix, and nwjs crashes if [the line](https://github.com/exos/node-webkit-fdialogs/commit/4ba597c44ad4162f8c66a56e4a5d05636d489f0#diff-025b14d5d2e91d029d15c4e4a0dbbcb8R67) that appends to the `files` gets executed (using nwjs 0.12.1 on Mac OS X 10.9.2).
I'm not sure if this is because the list is readonly or because we are trying to put a non-File instance there (the `{ _iAmNotAFile: true }` object gets there in my setup).

**Comment by sompylasar** [comment]
@exos, I've managed to find another solution which seems to work.

I've found an event that is triggered when the file dialog gets closed, so we can handle the "change" even if the file input value hasn't actually changed.

Instead of the following lines:

``` javascript
    this.element.addEventListener('change', function (ev) {
        self.emit('element-change', ev, this.element);
    });
```

use the following code (btw, `ev` and `element` aren't used in the 'element-change' handler now):

``` javascript
    // Get the reference to the nwjs window object (not the DOM window).
    var gui = this.window.require('nw.gui');
    var win = gui.Window.get();
    // Handle the nwjs window focus event (triggered after the file selection dialog is closed).
    win.on('focus', function() {
      // Add a delay to handle the change after the selected file path is assigned to the element's value.
      setTimeout(function () {
        self.emit('element-change', /* ev = */ {}, /* element = */ self.element);
      }, 0);
    });
```

Also I looked throughout the code and found an inconsistency ( `= window.document.createAttribute(` instead of `= this.window.document.createAttribute(` ), a memory leak ( `this.element = null;` unreachable ) , and a typo ( `this.name = 'NoSoelectedFile';` ).

**Comment by sompylasar** [comment]
@exos Please review the PR https://github.com/exos/node-webkit-fdialogs/pull/6

**Comment by exos** [comment]
Checking for #6
