### ISSUE TITLE
Save files with BOM?

### ISSUE THREAD

**Issue by craigshoemaker** [exos/node-webkit-fdialogs#3]
Is the an option to save files with [BOM](http://en.wikipedia.org/wiki/Byte_order_mark)?

**Comment by craigshoemaker** [comment]
Well I just went and read the code and see that there is no option :smile:. Perhaps if I have the time later I can provide a pull request.

**Comment by exos** [comment]
Library was created for easy dialogs usage on node-webkit. To save and read files it use the native node.js filesystem module as you can see in [line 221 of lib/fdialog.js](https://github.com/exos/node-webkit-fdialogs/blob/develop/lib/fdialog.js#L221).

Content is sent throug a Buffer object (Node.js native) and it defines the encoding and staf. For easy2use reazons I have included the string, and encoding's method to save that. But you can create a Buffer and send it to saveFile method directly (just for binary formats).

There is an ISSUE on node adding UTF8 encoding with BOM here: joyent/node#4039
And there is more here: joyent/node#1918
Here is a tool for it: https://www.npmjs.com/package/iconv-lite
